server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webgis
    username: webgis
    password: webgis123
    driver-class-name: org.postgresql.Driver

mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml
